# Generated by Django 6.0.1 on 2026-01-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.TextField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(default="", max_length=50),
        ),
    ]
