# Generated by Django 6.0.1 on 2026-01-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_telegram_chat_id_alter_user_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_token",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
